product_id: 0x0006

shoulder_roll_driver:
  joint_name: shoulder_roll_joint
  id: 21
  min_angle: -320
  max_angle: 320
  stretch: 60
  speed: 127
  current_limit: 3000
  temprature_limit: 80

shoulder_pitch_driver:
  joint_name: shoulder_pitch_joint
  id: 1
  min_angle: -90
  max_angle: 90
  stretch: 60
  speed: 127
  current_limit: 3000
  temprature_limit: 80

elbow_pitch_driver:
  joint_name: elbow_pitch_joint
  id: 2
  min_angle: 0
  max_angle: 180
  stretch: 60
  speed: 127
  current_limit: 3000
  temprature_limit: 80

wrist_pitch_driver:
  joint_name: wrist_pitch_joint
  id: 3 
  min_angle: -90
  max_angle: 90
  stretch: 60
  speed: 127
  current_limit: 3000
  temprature_limit: 80

wrist_yaw_driver:
  joint_name: wrist_yaw_joint
  id: 4
  min_angle: -90
  max_angle: 90
  stretch: 60
  speed: 127
  current_limit: 3000
  temprature_limit: 80

wrist_roll_driver:
  joint_name: wrist_roll_joint
  id: 5
  min_angle: -320
  max_angle: 320
  stretch: 60
  speed: 127
  current_limit: 3000
  temprature_limit: 80

